#!/bin/bash

# Deployment script for Supabase Edge Functions
# Since local Docker deployment isn't available, these functions need to be deployed manually

echo "=== Supabase Edge Functions Deployment Guide ==="
echo ""
echo "The following functions have been updated and need deployment:"
echo ""
echo "1. AUTH FUNCTION (supabase/functions/auth/index.ts)"
echo "   - Removed referrals table insertion during registration"
echo "   - Added referrals table insertion during membership activation"
echo "   - Referral system now only for activated members"
echo ""
echo "2. ADMIN-CLEANUP FUNCTION (supabase/functions/admin-cleanup/index.ts)"
echo "   - Separated from auth flow"
echo "   - Protects users with root referrer from cleanup"
echo ""
echo "MANUAL DEPLOYMENT STEPS:"
echo "1. Go to Supabase Dashboard > Edge Functions"
echo "2. Update or create 'auth' function with content from supabase/functions/auth/index.ts"
echo "3. Update or create 'admin-cleanup' function with content from supabase/functions/admin-cleanup/index.ts"
echo ""
echo "PROJECT DETAILS:"
echo "- Project Ref: cvqibjcbfrwsgkvthccp"
echo "- Project URL: https://cvqibjcbfrwsgkvthccp.supabase.co"
echo ""
echo "Environment Variables needed:"
echo "- SUPABASE_URL: https://cvqibjcbfrwsgkvthccp.supabase.co"
echo "- SUPABASE_SERVICE_ROLE_KEY: [Your service role key]"
echo "- ADMIN_SECRET_KEY: beehive-admin-secret"